### ISSUE TITLE
Unable to build ringOS-Beta17 image from existing Makefile

### ISSUE THREAD

**Issue by wmthornton** [Andrej123456789/ringOS#12]
**Describe the bug**
When working on compiling an image for ringOS-Beta17 I am unable to successfully build them image using the existing Makefile. The kernel compiles and links successfully when the command "make kernel" is issued from within the ringOS-Beta17 directory. When I then issue the "make buildimg" command I receive the following output:

wmthornton@vostro-3500:~/Desktop/source/repos/ringOS/ringOS-Beta17$ make buildimg
dd if=/dev/zero of=bin/ringOS.img bs=512 count=93750
93750+0 records in
93750+0 records out
48000000 bytes (48 MB, 46 MiB) copied, 0.705147 s, 68.1 MB/s
mformat -i bin/ringOS.img -F ::
mmd -i bin/ringOS.img ::/EFI
mmd -i bin/ringOS.img ::/EFI/BOOT
mcopy -i bin/ringOS.img ../gnu-efi/x86_64/bootloader/main.efi ::/EFI/BOOT
../gnu-efi/x86_64/bootloader/main.efi: No such file or directory
make: *** [Makefile:61: buildimg] Error 1

What steps do I need to take to successfully compile and build the image on Ubuntu 20.04? The directories that the Makefile is referencing do not exist in the repository so I'm unsure what to do next.

**Version of ringOS**
Beta17

**Expected behavior**

**Screenshots**

![Screenshot from 2022-01-14 18-50-52](https://user-images.githubusercontent.com/16928193/149604470-3bea8148-3cde-483b-b238-0da8b9d0de76.png)

**Additional context**
When I attempt to build the bootloader code contained in the "ringOS-Beta17-bootloader" it fails to compile so I don't even have the correct bootloader to build an image with.

![Screenshot from 2022-01-14 18-58-36](https://user-images.githubusercontent.com/16928193/149604669-2a8b7e6e-7889-4491-937a-0f703eb9d660.png)

**Comment by Andrej123456789** [comment]
Hello. I know what is a problem. 

`git clone https://github.com/VanGutan/gnu-efi-files` 

Create one ringOS folder, this cloned repo rename as `gnu-efi`, `ringOS-beta17` rename as `kernel` and clone `git clone https://github.com/VanGutan/ringOS-Beta14-OVMFTemplate` and rename as `OVMFbin`.
Copy `ringOS-Beta17-bootloader` folder into `gnu-efi` folder and rename it to `bootloader`.

Now try compile.

**Comment by wmthornton** [comment]
That solved the issue and the code compiled successfully. I will close this issue.
