### ISSUE TITLE
Why not Makefile clone the bootloader automaticly?

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Andrej123456789/ringOS#13]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when people just don't follow the instruction and read the documentation.

**Describe the solution you'd like**
Why don't just put the cloning in the Makefile?

**Describe alternatives you've considered**
During build, it will check for the bootloader folder and if it does not exist, it will clone the repo

**Additional context**
None

**Comment by Andrej123456789** [comment]
Existing Makefile is used when you have bootloader but I will add this feature

**Comment by ElectroBoy404NotFound** [comment]
Ok Thanks!

**Comment by Andrej123456789** [comment]
https://github.com/ringwormGO-organization/ringOS/commit/fb57b3961f5ce1e30b4ebf70aac91b40617e4cb5

**Comment by Andrej123456789** [comment]
Task finished
Issue will be closed

**Comment by ElectroBoy404NotFound** [comment]
Ok nice!
