### ISSUE TITLE
Mouse does not work in builder

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Andrej123456789/ringOS#15]
**Version of ringOS**
what ever the builder gives

**Unexpected behavior**
mouse to not work

**Expected behavior**
mouse to work

**Screenshots**

**Additional context**

**Comment by Andrej123456789** [comment]
How mouse don't work.
Where you run ringOS

**Comment by ElectroBoy404NotFound** [comment]
> How mouse don't work. Where you run ringOS

the builder altamaticly ran it in qemu

**Comment by StjepanBM1** [comment]
Well, what did you do when the OS booted?

**Comment by ElectroBoy404NotFound** [comment]
> Well, what did you do when the OS booted?

I clicked on the window

**Comment by Andrej123456789** [comment]
Are you tried to use GUI.
Position is not 100% precise, so try click again around area

**Comment by StjepanBM1** [comment]
OK so ringOS booted in QEMU, right? And you clicked on the window, what did you do to find out that mouse isn't working?

**Comment by ElectroBoy404NotFound** [comment]
> OK so ringOS booted in QEMU, right? And you clicked on the window, what did you do to find out that mouse isn't working?

yes. Move it like 100 meters left, right, top, bottom

**Comment by ElectroBoy404NotFound** [comment]
> Are you tried to use GUI. Position is not 100% precise, so try click again around area

 which gui?

**Comment by Andrej123456789** [comment]
StartMenu, window

**Comment by ElectroBoy404NotFound** [comment]
> StartMenu, window

linux....

**Comment by Andrej123456789** [comment]
When mouse don't work

**Comment by ElectroBoy404NotFound** [comment]
OS, ringOS builder one

**Comment by Andrej123456789** [comment]
Mouse is part of operating system

**Comment by ElectroBoy404NotFound** [comment]
i know

**Comment by Andrej123456789** [comment]
What don't work

**Comment by ElectroBoy404NotFound** [comment]
the mouse in the ringos

**Comment by Andrej123456789** [comment]
When stop working

**Comment by ElectroBoy404NotFound** [comment]
It was never working

**Comment by Andrej123456789** [comment]
Try reboot

**Comment by ElectroBoy404NotFound** [comment]
Tried x2

**Comment by Andrej123456789** [comment]
Press middle button to start it

**Comment by ElectroBoy404NotFound** [comment]
> Press middle button to start it

scroll button?

**Comment by Andrej123456789** [comment]
Yes

**Comment by ElectroBoy404NotFound** [comment]
> Yes

ok wait

**Comment by ElectroBoy404NotFound** [comment]
Only key presses are getting registered, when i move the mouse nothing happens, i tried pressing the mouse buttons also.. Going through the code.

**Comment by Andrej123456789** [comment]
Film a video

**Comment by ElectroBoy404NotFound** [comment]
ok

**Comment by ElectroBoy404NotFound** [comment]
Went through the code, turns out that the ringos builder does not support mouse as Beta14 did not have it. Closing....
