### ISSUE TITLE
Unable to build beta17

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Andrej123456789/ringOS#16]
**Describe the bug**
i CDed into ringOS-Beta17 and ran make buildimg and it tries to go to ../gnu-efi??? should'nt it go to ringOS-Beta17-bootloader?

**Version of ringOS**
Beta17

**Expected behavior**
This not to happen

**Screenshots**

**Additional context**

**Comment by Andrej123456789** [comment]
https://github.com/ringwormGO-organization/ringOS/issues/12

**Comment by Andrej123456789** [comment]
Check this issue and come back

**Comment by ElectroBoy404NotFound** [comment]
> #12

Oof my bad
