### ISSUE TITLE
Beta17 not booting compleatly

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Andrej123456789/ringOS#17]
**Describe the bug**
Bootloader says "GOP Located" and reboots and sometimes it shows Could not load BMP image. but the image is in the ISO.

**Version of ringOS**
Beta17

**Expected behavior**
it to load

**Screenshots**

**Additional context**

**Comment by Andrej123456789** [comment]
Did you run operating system on real hardware

**Comment by Andrej123456789** [comment]
Could we finish your Pull Request

**Comment by ElectroBoy404NotFound** [comment]
No, on qemu

**Comment by ElectroBoy404NotFound** [comment]
> Could we finish your Pull Request

that was Beta14

**Comment by Andrej123456789** [comment]
https://github.com/ringwormGO-organization/ringOS/pull/14

**Comment by ElectroBoy404NotFound** [comment]
comming

**Comment by Andrej123456789** [comment]
> No, on qemu
How many RAM you give, also try change pictures

**Comment by Andrej123456789** [comment]
> > No, on qemu


How many RAM you give, also try change pictures

**Comment by ElectroBoy404NotFound** [comment]
> > > No, on qemu
> 
> How many RAM you give, also try change pictures

3GB. Cant put images

**Comment by ElectroBoy404NotFound** [comment]
![Screenshot from 2022-01-17 19-44-47](https://user-images.githubusercontent.com/89782177/149785819-0de0e1c3-ffe2-4f14-b0ff-9bfd4c78f9d6.png)
Last frame it shows before restarting

**Comment by Andrej123456789** [comment]
How you start Qemu

**Comment by ElectroBoy404NotFound** [comment]
make run

**Comment by Andrej123456789** [comment]
Is this command same as in Makefile

**Comment by Andrej123456789** [comment]
qemu-system-x86_64 -machine q35 -drive file=$(BUILDDIR)/$(OSNAME).img -m 3G -cpu qemu64 -drive if=pflash,format=raw,unit=0,file="$(OVMFDIR)/OVMF_CODE-pure-efi.fd",readonly=on -drive if=pflash,format=raw,unit=1,file="$(OVMFDIR)/OVMF_VARS-pure-efi.fd" -net none

**Comment by ElectroBoy404NotFound** [comment]
yes

**Comment by Andrej123456789** [comment]
Check your bootloader and is picture set to Picture.bmp

**Comment by ElectroBoy404NotFound** [comment]
checking

**Comment by ElectroBoy404NotFound** [comment]
yes it is, but i just realized that it was named as "Test.bmp" in the ISO!

**Comment by ElectroBoy404NotFound** [comment]
now i dont have any of those errors and the BMP gets loaded before it again reboots

**Comment by Andrej123456789** [comment]
Download code again

**Comment by ElectroBoy404NotFound** [comment]
tried

**Comment by Andrej123456789** [comment]
Download bootloader again

**Comment by Andrej123456789** [comment]
https://github.com/VanGutan/gnu-efi

**Comment by Andrej123456789** [comment]
And come back later

**Comment by ElectroBoy404NotFound** [comment]
tried

**Comment by ElectroBoy404NotFound** [comment]
Why close? this issue is still not compleate!

**Comment by hahahahacker2009** [comment]
Please, check your spelling before posing on GitHub and read the docs carefully.

**Comment by ElectroBoy404NotFound** [comment]
> Please, check your spelling before posing on GitHub and read the docs carefully.

*complete
