### ISSUE TITLE
Uppercase signs don't work

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Andrej123456789/ringOS#21]
**Describe the bug**
When i try "!" it shows "TM"

**Version of ringOS**
ringos stable 1

**Expected behavior**
it to show !

**Screenshots**

**Additional context**

**Comment by Andrej123456789** [comment]
This is more feature request

**Comment by ElectroBoy404NotFound** [comment]
This is an bug...

**Comment by StjepanBM1** [comment]
It isn't a bug it is a feature. Uppercase sings will be added in stable version 2.

**Comment by ElectroBoy404NotFound** [comment]
> It isn't a bug it is a feature. Uppercase sings will be added in stable version 2.

Oh ok
