### ISSUE TITLE
ringOS GUI stopes working after resizing the window

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Andrej123456789/ringOS#22]
**Describe the bug**
I went into the settings and resized the OVMF screen size and now it is not booting (almost like my old issue, but i opened a new one)

**Version of ringOS**
Beta17

**Expected behavior**
nothing to happen and everything to work

**Screenshots**
See my last issue

**Additional context**
It happens only is i resize it smaller than the image.

**Comment by Andrej123456789** [comment]
Did you get Page Fault

**Comment by ElectroBoy404NotFound** [comment]
No, it just hangs after bootloader loads the img

**Comment by Andrej123456789** [comment]
Send screenshot

**Comment by ElectroBoy404NotFound** [comment]
ok wait

**Comment by Andrej123456789** [comment]
Maybe I fixed during live stream

**Comment by ElectroBoy404NotFound** [comment]
![Screenshot from 2022-01-22 18-20-20](https://user-images.githubusercontent.com/89782177/150639207-fb7001ba-21b1-478e-bd38-ab2f2192ec74.png)

**Comment by ElectroBoy404NotFound** [comment]
> Maybe I fixed during live stream

The image is not even rendering in the stream

**Comment by Andrej123456789** [comment]
> > Maybe I fixed during live stream
> 
> The image is not even rendering in the stream

Go to the start of stream. I set it up when picture will draw

**Comment by ElectroBoy404NotFound** [comment]
> > > Maybe I fixed during live stream
> > 
> > 
> > The image is not even rendering in the stream
> 
> Go to the start of stream. I set it up when picture will draw

ok

**Comment by ElectroBoy404NotFound** [comment]
Update: Again problem with BMP images...

**Comment by ElectroBoy404NotFound** [comment]
nothing

**Comment by ElectroBoy404NotFound** [comment]
Seems like the kernel is not loading

**Comment by Andrej123456789** [comment]
Try again after stream

**Comment by Andrej123456789** [comment]
Then I will upload code

**Comment by ElectroBoy404NotFound** [comment]
ok

**Comment by ElectroBoy404NotFound** [comment]
Update: Went though the code and found out that there is an switch case which has only a few resulutions. Which is the problem. And also, resizing it to a size smaller than the image makes the image throw an Kernel panic due to it over writing the video buffer where there is no video buffer.

**Comment by Andrej123456789** [comment]
Use 1024x768

**Comment by Andrej123456789** [comment]
Or create Pull Request :)

**Comment by ElectroBoy404NotFound** [comment]
> Use 1024x768


Kernel panic

**Comment by Andrej123456789** [comment]
I can't print resolution properly

**Comment by ElectroBoy404NotFound** [comment]
ok

**Comment by ElectroBoy404NotFound** [comment]
#23

**Comment by ElectroBoy404NotFound** [comment]
Fixes crashing

**Comment by ElectroBoy404NotFound** [comment]
Closing this as this was fixed in live stream

**Comment by ElectroBoy404NotFound** [comment]
UI (buttons etc) dont work in resulutions less than 1024x768

**Comment by ElectroBoy404NotFound** [comment]
Update: Sub-Menu buttons dont work

**Comment by Andrej123456789** [comment]
I am working on it

**Comment by ElectroBoy404NotFound** [comment]
Ignore it, it is not implemented i guess

**Comment by ElectroBoy404NotFound** [comment]
> I am working on it

ok

**Comment by Andrej123456789** [comment]
Upload bot code

**Comment by ElectroBoy404NotFound** [comment]
> Upload bot code

Sorry, cant. The server stopped working (hard drive fail).

**Comment by ElectroBoy404NotFound** [comment]
#24 Fixes a part of GUI and fixes resolution rendering

**Comment by Andrej123456789** [comment]
@StjepanBM1 We have project status instead so many labels

**Comment by Andrej123456789** [comment]
I think now will work

**Comment by ElectroBoy404NotFound** [comment]
@StjepanBM1 I already fixed it
@Andrej123456789 Thank you for closing this issue! have a great time!
