### ISSUE TITLE
Add Makefile for BIOS version, and guide to compile and use

### ISSUE THREAD

**Issue by hahahahacker2009** [Andrej123456789/ringOS#3]
You should add a makefile, it is easier to compile your operating system. Also, add the guide to compile and use.

**Comment by Andrej123456789** [comment]
Today coming documentation

**Comment by Andrej123456789** [comment]
Issue is reopen because ringwormGO still don't have Makefile for BIOS version

**Comment by Andrej123456789** [comment]
Sorry, only way to compile ringOSY is using Docker

**Comment by hahahahacker2009** [comment]
Makefile is just the builder with other syntax

**Comment by Andrej123456789** [comment]
I know that

**Comment by Andrej123456789** [comment]
Currently we can't find proper compiler to use in Makefile

**Comment by Andrej123456789** [comment]
We are again working on non-Docker compiler enviroment

**Comment by Andrej123456789** [comment]
https://github.com/ringwormGO-organization/ringOS/blob/main-and-beta-things/ringOSY/README.md#non-docker-build-enviroment

Fixed

**Comment by Andrej123456789** [comment]
Issue will be closed

**Comment by Andrej123456789** [comment]
Issue is moved

**Comment by Andrej123456789** [comment]
It's half of fixed

**Comment by ElectroBoy404NotFound** [comment]
> Currently we can't find proper compiler to use in Makefile



> It's half of fixed

But does'nt it mean that i cant compile it on windows anymore?

**Comment by Andrej123456789** [comment]
You need Docker

**Comment by ElectroBoy404NotFound** [comment]
I know
