### ISSUE TITLE
Make .sh build script for Fedora / CentOS (Stream) / RHEL

### ISSUE THREAD

**Issue by hahahahacker2009** [Andrej123456789/ringOS#30]
Hi,

I'm currently running Centstream 9 and I'm having problems when building ringOS from source because it only support building on Debian or Debian-based distribution. The shell script for building ringOS doesn't support Fedora-based distribution including Centstream, RHEL, Alma, Rocky. Can you make a specified shell script for them?

Suggestion: you can make a script called configure-debian(.sh) and configure-rhel(.sh) and the configure(.sh) script to detect if it is Debian or Fedora/RHEL based distribution. Those script throw information about the current operating system to know how to build it. The build.sh or Makefile will choose the way to build based on the info about operating system. configure scripts are optionally use to install required packages. 

Hope my issue will be fixed soon.

**Comment by Andrej123456789** [comment]
If you already running Centstream 9 you could create shell script because I am running only Debian based distros but I have plan for Arch based distros.

**Comment by hahahahacker2009** [comment]
Help me with packages

**Comment by Andrej123456789** [comment]
I don't know Cent, use internet

**Comment by StjepanBM1** [comment]
If you are using CentOS / Fedora you might be able to do it your self. If you can't do it your self respond to this comment and I will fix it
