### ISSUE TITLE
ringOS Limine make dosen't work

### ISSUE THREAD

**Issue by StjepanBM1** [Andrej123456789/ringOS#31]
When I tried to compile ringOS Limine it didn't work. I followed all of the instructions but it couldn't compile.

Here are some of the issues:
**1. limine/limine-s2deploy dosen't exist**
Error below;
```
   limine/limine-s2deploy barebones.iso
   make: limine/limine-s2deploy: No such file or directory
   make: *** [GNUmakefile:40: barebones.iso] Error 127
```

**2. When limine-s2deploy is manually created it still doesn't compile (tried it with sudo it still didn't work)**
Error below;
```
   make: limine/limine-s2deploy: Permission denied
   make: *** [GNUmakefile:40: barebones.iso] Error 127
```

**Comment by Andrej123456789** [comment]
https://github.com/limine-bootloader/limine#biosuefi-hybrid-iso-creation
Check this about `limine-deploy`

**Comment by Andrej123456789** [comment]
And type `git pull` to fetch new commits

**Comment by StjepanBM1** [comment]
It still doesn't work
```
kernel.c:148: undefined reference to `kernel_start'
```

**Comment by Andrej123456789** [comment]
Send me Makefile, linker and shell script which you use

**Comment by Andrej123456789** [comment]
Your files will not be needed

**Comment by Andrej123456789** [comment]
I had same issue as you but now I fixed so I think now when you get new code you will be able to compile
