### ISSUE TITLE
(real hardware) OS stopes booting and freezes

### ISSUE THREAD

**Issue by ElectroBoyCodes** [Andrej123456789/ringOS#33]
**Describe the bug**
I got the OS to boot on real hardware, but it showed the PCI stuff and then the task bar and it froze. No mouse, no keyboard, nothing, just frozen as if it was displaying an image. And also, there was an error:
```
An error occurred while attempting to load BMP file!
Loading file from media!
Could not load BMP image
```

**Version of ringOS**
Commit <a href="https://github.com/ringwormGO-organization/ringOS/commit/d86bc43ab2c0952b8391210f96b2e74bafebd8d3">476</a>

**Expected behavior**
Everything to work

**Screenshots**
Cant add rightnow

**Additional context**

Hardware

1. Ram

- Type:    DDR3
- Speed: 3.666GHz
- Total:   6144MB
- Slot1:   2048MB
- Slot2:   4096MB

2. Laptop

- Samsung NP300E5X-S01IN

3. GPU

- Intel integrated graphics
- Nvidia GeForce 610M 1GB DDR3

4. Processor:
 
- Model:            Intel Core i5 (3rd Generation)
- Clock Speed:  2.5GHz
- Cores:             2

5. Connected Storage:

- [ ] Sata HHD
- [ ] Sata SSD
- [ ] Sata Disk Drive
- [X] USB pen drive

**Comment by ElectroBoyCodes** [comment]
Wait, is it because im using an usb keyboard? But the mouse should work

**Comment by ElectroBoyCodes** [comment]
The mouse connected is the internal track pad

**Comment by Andrej123456789** [comment]
I think I said ringOS don't work on real hardware but I am not a quite sure why ringOS can't load BMP images

**Comment by Andrej123456789** [comment]
Actually ringOS can work on real hardware if it is not over 3GB, but never come to image loading part

**Comment by ElectroBoyCodes** [comment]
> I think I said ringOS don't work on real hardware 

You did

>  but I am not a quite sure why ringOS can't load BMP images 

ok

Also, the os crashes on VM also (atlease from what i remember from like the starting of 2022)

**Comment by ElectroBoyCodes** [comment]
> Actually ringOS can work on real hardware if it is not over 3GB, but never come to image loading part

Ok, i will remove the 4GB stick and try

**Comment by Andrej123456789** [comment]
Also can you try ringOS stable version 2 because now calculator has some bugs

**Comment by ElectroBoyCodes** [comment]
> Also can you try ringOS stable version 2 because now calculator has some bugs

ok

**Comment by ElectroBoyCodes** [comment]
@Andrej123456789 Tried ringOS latest on 2GB ram and it just rebooted. I will try stable version 2 in a few mins

**Comment by Andrej123456789** [comment]
Can you upload video?

**Comment by ElectroBoyCodes** [comment]
> Can you upload video?

Sorry, my tab has no more battery

**Comment by Andrej123456789** [comment]
What text can you see

**Comment by ElectroBoyCodes** [comment]
Also, im unable to flash the ISO using etcher. Idk why.

**Comment by ElectroBoyCodes** [comment]
> What text can you see

It goes too fast

**Comment by Andrej123456789** [comment]
> Also, im unable to flash the ISO using etcher. Idk why.

etcher is even not supported but you can manually copy files

**Comment by Andrej123456789** [comment]
> @Andrej123456789 Tried ringOS latest on 2GB ram and it just rebooted. I will try stable version 2 in a few mins

So even on 2GB of RAM? Can you try with 4GB exactly?

**Comment by ElectroBoyCodes** [comment]
> etcher is even not supported but you can manually copy files

ok

**Comment by ElectroBoyCodes** [comment]
> > @Andrej123456789 Tried ringOS latest on 2GB ram and it just rebooted. I will try stable version 2 in a few mins
> 
> So even on 2GB of RAM? Can you try with 4GB exactly?

ok wait, i need to reflash the old one

**Comment by Andrej123456789** [comment]
> 

See documentation for copying boot files

**Comment by ElectroBoyCodes** [comment]
@Andrej123456789 with 6GB, it froze after loading the taskbar

**Comment by Andrej123456789** [comment]
So you come to the taskbar point?

**Comment by Andrej123456789** [comment]
Yes

**Comment by ElectroBoyCodes** [comment]
> So you come to the taskbar point?

Yes i think

**Comment by ElectroBoyCodes** [comment]
> Yes

ok

**Comment by Andrej123456789** [comment]
Try remove USB stuff

**Comment by ElectroBoyCodes** [comment]
> Try remove USB stuff

I only have the USB disk

**Comment by Andrej123456789** [comment]
Use ringOS stable 2 now

**Comment by ElectroBoyCodes** [comment]
> Use ringOS stable 2 now

Will try, wait

**Comment by Andrej123456789** [comment]
> > Try remove USB stuff
> 
> I only have the USB disk

USB keyboard

**Comment by ElectroBoyCodes** [comment]
> > > Try remove USB stuff
> > 
> > 
> > I only have the USB disk
> 
> USB keyboard

Tried without it also

**Comment by Andrej123456789** [comment]
Do you see taskbar

**Comment by ElectroBoyCodes** [comment]
> Do you see taskbar

Yes

**Comment by ElectroBoyCodes** [comment]
Im about to boot stable 2

**Comment by Andrej123456789** [comment]
Ok

**Comment by ElectroBoyCodes** [comment]
@Andrej123456789 The OS keeps rebooting on 2GB, 4GB and 6GB

**Comment by Andrej123456789** [comment]
If you can debug on real hardware I will appriciate

**Comment by Andrej123456789** [comment]
Also tomorrow I will ask you more questions so check this issue often these days

**Comment by Andrej123456789** [comment]
And try 1GB if you can

**Comment by ElectroBoyCodes** [comment]
> Also tomorrow I will ask you more questions so check this issue often these days

Ok

**Comment by Andrej123456789** [comment]
> > If you can debug on real hardware I will appriciate
> 
> I would like to know how to do it

Search for interent

**Comment by Andrej123456789** [comment]
I think you need serial cable and try 1GB of RAM

**Comment by ElectroBoyCodes** [comment]
> And try 1GB if you can

I dont have a 1GB stick

**Comment by ElectroBoyCodes** [comment]
> I think you need serial cable and try 1GB of RAM

This laptop motherboard does not have a serial port (not even Test pads)

**Comment by Andrej123456789** [comment]
Ok then

**Comment by Andrej123456789** [comment]
See you later

**Comment by ElectroBoyCodes** [comment]
Bye

**Comment by ElectroBoyCodes** [comment]
@Andrej123456789 Cant debug on my hardware

**Comment by ElectroBoyCodes** [comment]
@Andrej123456789 Hello? Where are the questions?

**Comment by ElectroBoyCodes** [comment]
@Andrej123456789

**Comment by ElectroBoyCodes** [comment]
here is the error:
https://drive.google.com/file/d/1GYzp11DQ3pMg3E6BgHRjMUxtEhpnyKSq/view?usp=sharing

**Comment by hahahahacker2009** [comment]
Please don't make a chat on GitHub via issue. Only answer to necessary question and avoid "ok". Also try to put as most as possible details.

**Comment by ElectroBoyCodes** [comment]
> Please don't make a chat on GitHub via issue. Only answer to necessary question and avoid "ok". Also try to put as most as possible details.

ok

**Comment by Andrej123456789** [comment]
Limine development is in very good situation so I think this issue will be solved when ringOS switch to Limine. I hope this will happen soon

**Comment by ElectroBoy404NotFound** [comment]
oh nice, also i cant  test the os on the hardware (the mother board died)

**Comment by hahahahacker2009** [comment]
I tested ringOS on real hardware and this is the result:

If you use `dd` to write ringOS.iso to an usb stick
`dd if=ringOS.iso of=/dev/sdb oflag=direct`

It won't even detect the disk.

You must mount ringOS.iso and copy ringOS.img out, use it to write to the disk.

`dd if=ringOS.img of=/dev/sdb oflag=direct`

Write: Success
Detect: Success
Boot: Success
Load all feature: Failure

It prints something about ringOS and load kernel, but it lasts for ~3 secs, automatically boot into the next boot order.

That's the issue I have.
ringOS version: ringOS "stable" 2.0.0 at https://github.com/ringwormGO-organization/ringOS/releases/tag/ringOSv2.0.0

**Comment by Andrej123456789** [comment]
Anyway this issue, we hope, will be fixed when ringOS with Limine bootloader came out

**Comment by ElectroBoy404NotFound** [comment]
Write: Success
Detect: Success
Boot: Success
Load all feature: Failure

It prints something about ringOS and load kernel, but it lasts for ~3 secs, automatically boot into the next boot order.

That's the issue I have.


>> It is same for me

**Comment by hahahahacker2009** [comment]
> Write: Success Detect: Success Boot: Success Load all feature: Failure
> 
> It prints something about ringOS and load kernel, but it lasts for ~3 secs, automatically boot into the next boot order.
> 
> That's the issue I have.
> 
> > > It is same for me

> We would wait for the paging feature to be fixed and ringOS comes with Limine bootloader.

**Comment by Andrej123456789** [comment]
ringOS Limine is working but because it is in early development there a lot of missing features. You can boot it. Paging is missing feature which will come later but we hope operating system will be usable because of Limine

**Comment by StjepanBM1** [comment]
This issue will be fixed with Limine release of ringOS. Until then please wait

**Comment by StjepanBM1** [comment]
So consider this issue fixed

**Comment by hahahahacker2009** [comment]
This issue can be closed with "Issue make an idea for future development" and "wontfix"

**Comment by Andrej123456789** [comment]
I will reopen this if Limine fail. Also I will lock this because there too much messages now
