### ISSUE TITLE
Can't boot in VMWare, VirtualBox and Hyper-V

### ISSUE THREAD

**Issue by hahahahacker2009** [Andrej123456789/ringOS#4]
Hyper-V:
![image](https://user-images.githubusercontent.com/86903124/143845369-c9651232-d47f-4509-9faa-2c9e1459e0e2.png)

Vbox:

![image](https://user-images.githubusercontent.com/86903124/143845388-f85097ac-82e3-4bf3-abd1-2946a5e773fb.png)
![image](https://user-images.githubusercontent.com/86903124/143845411-2720b4ef-5bc6-421b-bfb5-a2662947a1c7.png)

Sorry I dont have vmware captures

**Comment by Andrej123456789** [comment]
Which config do you use

**Comment by Andrej123456789** [comment]
Hyper-V is not supproted, but we will fix it.

We just need more information about config you use in Virtual Box

**Comment by hahahahacker2009** [comment]
![image](https://user-images.githubusercontent.com/86903124/144178911-8fc57d46-a306-42ab-bd57-ed101cab26a4.png)
![image](https://user-images.githubusercontent.com/86903124/144178944-8f6d1c16-0c26-49ce-a1f0-c53c7edf32b9.png)
![image](https://user-images.githubusercontent.com/86903124/144178977-45ccbbd1-df44-4ac4-bd69-e5aac1310f0f.png)
![image](https://user-images.githubusercontent.com/86903124/144179010-4a58852e-c5fe-4a3a-8bc1-2519e1d6b30a.png)

**Comment by StjepanBM1** [comment]
Hello!
ringOS must be marked as Other 64 bit OS and ringOS will not use all 4GB of RAM 
You need 4GB if you don't want Page Fault and type is NOT *IBM OS/2*.

**Comment by StjepanBM1** [comment]
If you experience more issues contact me on ringwormGO discord server

**Comment by StjepanBM1** [comment]
Hey! Can you update me on your situation?

**Comment by hahahahacker2009** [comment]
I have already joined the server, now to test

**Comment by hahahahacker2009** [comment]
Now it just can't boot in VMWare and Hyper-V. I have configured VMWare to Other (64-bit) and Hyper-V to use Generation 2 but still can't

**Comment by Andrej123456789** [comment]
![image](https://user-images.githubusercontent.com/83548580/144573093-1c1f5fa7-d863-454e-8a1c-8fa837346c0c.png)
@Someone8859 send me this photo

**Comment by Andrej123456789** [comment]
You need VMWare Vorkstation Pro for this

**Comment by hahahahacker2009** [comment]
![image](https://user-images.githubusercontent.com/86903124/144574932-07c7f225-7458-4fe0-927c-401b156c330b.png)

**Comment by Andrej123456789** [comment]
You need VMWare Vorkstation Pro for running in VMWare

**Comment by Andrej123456789** [comment]
Also, Hyper-V is not supproted.

**Comment by Andrej123456789** [comment]
https://github.com/ringwormGO-organization/ringOS/issues/5

Use 4GB of RAM if virtual machine will allow

**Comment by hahahahacker2009** [comment]
This is when I run ringOS on VMWare pro and move the mouse

The pink "a" appear when I click and move the mouse
![image](https://user-images.githubusercontent.com/86903124/144745963-68f6b785-0401-456d-b222-c0cec08a64ff.png)

**Comment by Andrej123456789** [comment]
Good

**Comment by Andrej123456789** [comment]
Try reboot and be sure you don't click mouse

**Comment by Andrej123456789** [comment]
Mouse draw 'a' when it's pressed

**Comment by Andrej123456789** [comment]
You can successfully boot so this issue is fixed

Issue will be closed
