### ISSUE TITLE
ringOS will crash if I click the mouse in VirtualBox

### ISSUE THREAD

**Issue by hahahahacker2009** [Andrej123456789/ringOS#5]
![image](https://user-images.githubusercontent.com/86903124/144541748-d1a3fd4d-cf90-4d94-b741-dd62c782faaa.png)

**Comment by hahahahacker2009** [comment]
Just because ringOS can't handle when we click the mouse, it needs some drivers

**Comment by Andrej123456789** [comment]
How much RAM you give

**Comment by Andrej123456789** [comment]
Because off too much clicking and low RAM Page Fault happend.

**Comment by hahahahacker2009** [comment]
Just click one time, and I can't give it more than 2GB because my computer just have 4GB of memory

**Comment by Andrej123456789** [comment]
ringOS WILL NOT use all 4GB of RAM

**Comment by Andrej123456789** [comment]
Use Qemu

**Comment by Andrej123456789** [comment]
Try with 4GB RAM and come later

**Comment by Andrej123456789** [comment]
Issue is closed because 4GB RAM in Virtual Box is system requirement.

**Comment by Andrej123456789** [comment]
VMWare is more stable

**Comment by ElectroBoy404NotFound** [comment]
VituralBox is broken for some OSes, unfortanatly the way this kernel works, it is broken.

**Comment by ElectroBoy404NotFound** [comment]
Also, that is a page fault, so looks like vbox is messing the memory
